# deep_purple
foreground: &foreground "#bec4de"
background: &background "#030027"
black: &black "#00001d"
blue: &blue "#90b0ff"
green: &green "#49a078"
gray: &gray "#8c92ac"
orange: &orange "#d99058"
purple: &purple "#bf79bf"
red: &red "#9d5060"
yellow: &yellow "#cdb07f"
yellow_bright: &yellow_bright "#d7ba89"

k9s:
  body:
    fgColor: *foreground
    bgColor: *background
    logoColor: *green
  prompt:
    fgColor: *foreground
    bgColor: *background
    suggestColor: *orange
  info:
    fgColor: *gray
    sectionColor: *green
  dialog:
    fgColor: *black
    bgColor: *background
    buttonFgColor: *foreground
    buttonBgColor: *green
    buttonFocusFgColor: *black
    buttonFocusBgColor: *blue
    labelFgColor: *orange
    fieldFgColor: *blue
  frame:
    border:
      fgColor: *green
      focusColor: *green
    menu:
      fgColor: *gray
      keyColor: *yellow
      numKeyColor: *yellow
    crumbs:
      fgColor: *black
      bgColor: *green
      activeColor: *yellow
    status:
      newColor: *blue
      modifyColor: *green
      addColor: *gray
      pendingColor: *orange
      errorColor: *red
      highlightColor: *yellow
      killColor: *purple
      completedColor: *gray
    title:
      fgColor: *blue
      bgColor: *background
      highlightColor: *purple
      counterColor: *foreground
      filterColor: *blue
  views:
    charts:
      bgColor: *background
      defaultDialColors:
        - *green
        - *red
      defaultChartColors:
        - *green
        - *red
    table:
      fgColor: *yellow
      bgColor: *background
      cursorFgColor: *black
      cursorBgColor: *blue
      markColor: *yellow_bright
      header:
        fgColor: *gray
        bgColor: *background
        sorterColor: *orange
    xray:
      fgColor: *blue
      bgColor: *background
      cursorColor: *foreground
      graphicColor: *yellow_bright
      showIcons: false
    yaml:
      keyColor: *red
      colonColor: *gray
      valueColor: *gray
    logs:
      fgColor: *gray
      bgColor: *background
      indicator:
        fgColor: *blue
        bgColor: *background
    help:
      fgColor: *gray
      bgColor: *background
      indicator:
        fgColor: *blue
