#!/bin/bash
if [ -z "$venv" ]; then 
  echo "no venv defined"
  return 1
fi
if [ -z "$(ls $venv)" ]; then
  echo "venv is empty"
  return 1
fi
max=0
bn=
count=
for i in $venv/*; do
  bn=$(basename $i)
  count=${#bn}
  if [[ $count -gt $max ]]; then
    max=$count
  fi
done
for i in $venv/*; do
  if [ -e $i/bin/python ]; then
    version=$($i/bin/python -V | sed 's/Python //')
  else
    version="N/A"
  fi
  padding=$((max + 1))
  printf "%-${padding}s %s\n" $(basename $i) $version
done
