# Config version for compatibility and deprecations
# See: https://nikitabobko.github.io/AeroSpace/guide#config-version
# Fallback value (if you omit the key): config-version = 1
config-version = 2

# You can use it to add commands that run after AeroSpace startup.
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = []

# Start AeroSpace at login
start-at-login = true

# Automatically reload the config when the config file is saved
# After setting this to true, reload once manually to start the auto-reloading
auto-reload-config = false

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Fallback value (if you omit the key): on-focused-monitor-changed = []
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don't use this macOS feature, but accidentally hit cmd-h or cmd-alt-h key
# Also see: https://nikitabobko.github.io/AeroSpace/goodies#disable-hide-app
automatically-unhide-macos-hidden-apps = false

# List of workspaces that should stay alive even when they contain no windows,
# even when they are invisible.
persistent-workspaces = ["A", "S", "D", "F", "G"]

# A callback that runs every time binding mode changes
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# See: https://nikitabobko.github.io/AeroSpace/commands#mode
on-mode-changed = []

focus-follows-mouse.enabled = false

# Possible values: (qwerty|dvorak|colemak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
key-mapping.preset = 'qwerty'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See:
#                 https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
gaps.inner.horizontal = 0
gaps.inner.vertical =   0
gaps.outer.left =       0
gaps.outer.bottom =     0
gaps.outer.top =        0
gaps.outer.right =      0

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
# Fallback value (if you omit the key): mode.main.binding = {}
[mode.main.binding]
    # All possible modifiers: cmd, alt, ctrl, shift

    # All possible commands: https://nikitabobko.github.io/AeroSpace/commands

    # See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
    # You can uncomment the following lines to open up terminal with alt + enter shortcut
    # (like in i3)
    # alt-enter = '''exec-and-forget osascript -e \
    # 'tell application "Terminal" to tell (do script) to activate' '''
		ctrl-a = 'mode aerospace'

    # See: https://nikitabobko.github.io/AeroSpace/commands#mode
    ctrl-esc = 'mode service'

[mode.aerospace.binding]
		ctrl-a = 'mode AEROSPACE'
	
    # See: https://nikitabobko.github.io/AeroSpace/commands#layout
    slash = [ 'layout tiles horizontal vertical', 'mode main']

    # See: https://nikitabobko.github.io/AeroSpace/commands#focus
    h = [ 'focus left', 'mode main']
    j = [ 'focus down', 'mode main']
    k = [ 'focus up', 'mode main']
    l = [ 'focus right', 'mode main']

    # See: https://nikitabobko.github.io/AeroSpace/commands#move
    shift-h = [ 'move left', 'mode main']
    shift-j = [ 'move down', 'mode main']
    shift-k = [ 'move up', 'mode main']
    shift-l = [ 'move right', 'mode main']

    # See: https://nikitabobko.github.io/AeroSpace/commands#resize
    minus = [ 'resize smart -50', 'mode main']
    shift-equal = [ 'resize smart +50', 'mode main']

    # See: https://nikitabobko.github.io/AeroSpace/commands#workspace
    a = [ 'workspace A', 'mode main']
    s = [ 'workspace S', 'mode main']
    d = [ 'workspace D', 'mode main']
    f = [ 'workspace F', 'mode main']
    g = [ 'workspace G', 'mode main']

    # See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
    shift-a = [ 'move-node-to-workspace A', 'mode main']
    shift-s = [ 'move-node-to-workspace S', 'mode main']
    shift-d = [ 'move-node-to-workspace D', 'mode main']
    shift-f = [ 'move-node-to-workspace F', 'mode main']
    shift-g = [ 'move-node-to-workspace G', 'mode main']

    # See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
    tab = [ 'workspace-back-and-forth', 'mode main']

[mode.AEROSPACE.binding]
    # See: https://nikitabobko.github.io/AeroSpace/commands#layout
    slash = [ 'layout tiles horizontal vertical']

    # See: https://nikitabobko.github.io/AeroSpace/commands#focus
    h = [ 'focus left']
    j = [ 'focus down']
    k = [ 'focus up']
    l = [ 'focus right']

    # See: https://nikitabobko.github.io/AeroSpace/commands#move
    shift-h = [ 'move left']
    shift-j = [ 'move down']
    shift-k = [ 'move up']
    shift-l = [ 'move right']

    # See: https://nikitabobko.github.io/AeroSpace/commands#resize
    minus = [ 'resize smart -50']
    shift-equal = [ 'resize smart +50']

    # See: https://nikitabobko.github.io/AeroSpace/commands#workspace
    a = [ 'workspace A']
    s = [ 'workspace S']
    d = [ 'workspace D']
    f = [ 'workspace F']
    g = [ 'workspace G']

    # See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
    shift-a = [ 'move-node-to-workspace A']
    shift-s = [ 'move-node-to-workspace S']
    shift-d = [ 'move-node-to-workspace D']
    shift-f = [ 'move-node-to-workspace F']
    shift-g = [ 'move-node-to-workspace G']

    # See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
    tab = [ 'workspace-back-and-forth']

		esc = 'mode main'


# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
    esc = ['reload-config', 'mode main']
    r = ['flatten-workspace-tree', 'mode main'] # reset layout
    f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
    backspace = ['close-all-windows-but-current', 'mode main']

    # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
    #s = ['layout sticky tiling', 'mode main']

    alt-shift-h = ['join-with left', 'mode main']
    alt-shift-j = ['join-with down', 'mode main']
    alt-shift-k = ['join-with up', 'mode main']
    alt-shift-l = ['join-with right', 'mode main']
