[colors]
ansi = [
   # '#3e3e3e', # dark_gray
   '#222222', # dark_gray
   '#f15d22', # red
   '#6eaa76', # green
   '#d19a66', # yellow_orange
   '#18a9c7', # blue
   '#ad7fa8', # purple
   '#7ec589', # cyan
   '#c8c9c1', # white
]
brights = [
   '#98918d', # grey
   '#d16969', # light_red
   '#B5CEA8', # light_green
   '#eece61', # yellow
   '#81c8d6', # light_blue
   '#D16D9E', # magenta
   '#a1d5a9', # cyan
   '#d8dee9', # white
]

background = '#222222'
foreground = '#cccccc'

cursor_bg = '#7ec589'
cursor_border = '#7ec589'
cursor_fg = '#515052'

selection_bg = '#223E55'
selection_fg = '#787878'

[colors.indexed]

[metadata]
name = 'System76'
