[colors]
# ansi = [
#   '#8a91a9',
#   '#99362f',
#   '#919e72',
#   '#c9d5ab',
#   '#c2cade',
#   '#a9b5d9',
#   '#798364',
#   '#e4eee8',
# ]

# brights = [
#   '#8a91a9',
#   '#99362f',
#   '#919e72',
#   '#c9d5ab',
#   '#c2cade',
#   '#a9b5d9',
#   '#798364',
#   '#e4eee8',
# ]
ansi = [
   '#8a91a9', # dark_gray
   # '#a53949', # red # 165 57 73
   '#bc7871', # light_red # 188 120 113
   '#939d76', # green # 147 157 118
   '#b4a14b', # yellow # 180 161 75
   '#7c9ebb', # blue # 124 158 187
   '#615adf', # purple # 97 90 223
   '#7abc3b', # cyan # 122 188 59
   '#f9f9f9', # white
]
brights = [
   '#c3cadc', # grey # 195 202 220
   '#bc7871', # light_red # 188 120 113
   '#ccd5af', # light_green # 204 213 175
   '#dbc175', # yellow # 219 193 117
   '#90b8d8', # light_blue # 144 184 216
   '#935dde', # magenta # 147 93 222
   '#e3f06c', # cyan # 227 240 108
   '#ffffff', # white
]

background = '#1f1e1c' # 31 30 28
foreground = '#cad4ae' # 202 212 174

cursor_bg = '#cad4ae' # 202 212 174
cursor_border = '#cad4ae' # 202 212 174
cursor_fg = '#1f1e1c' # 31 30 28

selection_bg = '#8a91a9' # 138 145 169
selection_fg = '#1f1e1c' # 31 30 28

[colors.indexed]

[metadata]
name = 'Tyranitar'
